



export const projects = [
    {id: 1, 
        title: "MediaPlayer",
        discription: "This project was a school assignment during the introduction to JavaScript. The requirements were to create three media player buttons. Later I decided to improve on the project and make it play audio and video files." , 
        img: require("../assets/img/mediaPlayer.png"),
        git: true,
        gitLink: "https://github.com/P1wP/MediaPlayer",
        live: true,
        liveLink: "http://noob-at-work.com/noroff/profun/ca/index.html",
        html: true,
        js: true,
        react: false,
        sass: false,
        css: true,
        grunt: false,
        py: false,
        boot: false
    },
    {id: 2, 
        title: "Hangman Game",
        discription: "A Simple Hangman Game made using Vanilla Javascript" , 
        img: require("../assets/img/hangman.png"),
        git: true,
        gitLink: "https://github.com/P1wP/Hangman_Game",
        live: true,
        liveLink: "http://www.noob-at-work.com/fun/hangman/hang.html",
        html: true,
        js: true,
        react: false,
        sass: false,
        css: true,
        grunt: false,
        py: false,
        boot: false
    },
    {id: 3, 
        title: "Project creator",
        discription: "I got sick of creating the same files over and over again. So I decided to automate the process. By running the “py” file, A terminal will ask for a project name, whether or not it should include JQuery, Bootstrap, FontAwesome, and if it should start the SASS interpreter or not.", 
        img: require("../assets/img/projectCreator.png"),
        git: true,
        gitLink: "https://github.com/P1wP/basicWebTemplate",
        live: false,
        liveLink: "",
        html: false,
        js: false,
        react: false,
        sass: false,
        css: false,
        grunt: false,
        py: true,
        boot: false
    },
    {id: 4, 
        title: '"clone"',
        discription: "Use bootstrap and SASS to develop a website by following a design provided by the tutor." , 
        img: require("../assets/img/clone.png"),
        git: true,
        gitLink: "https://github.com/P1wP/CSS-Frameworks",
        live: true,
        liveLink: "http://www.noob-at-work.com/noroff/cssfra/ca/index.html",
        html: true,
        js: false,
        react: false,
        sass: true,
        css: false,
        grunt: false,
        py: false,
        boot: true
    },
    {id: 5, 
        title: '"clone" + React.js',
        discription: 'Re-did the "clone" project in React.js' , 
        img: require("../assets/img/clone.png"),
        git: true,
        gitLink: "https://github.com/P1wP/CSS-Frameworks",
        live: true,
        liveLink: "http://www.noob-at-work.com/noroff/cssfra/ca/index.html",
        html: false,
        js: false,
        react: true,
        sass: true,
        css: false,
        grunt: false,
        py: false,
        boot: true
    },
    {id: 6, 
        title: 'Exam_1',
        discription: 'This is my first year exam project. The task was to create a microsite for SpaceX or NASA. It goes without saying, this site is not affiliated with SpaceX nor NASA' , 
        img: require("../assets/img/exam_1.png"),
        git: true,
        gitLink: "https://github.com/P1wP/ExamYr1",
        live: true,
        liveLink: "http://www.noob-at-work.com/noroff/exam_semester1/index.html",
        html: true,
        js: true,
        react: false,
        sass: false,
        css: true,
        grunt: false,
        py: false,
        boot: false
    },
    {id: 7, 
        title: 'Color generator',
        discription: 'A JavaScript function that generates a random hex value. This value is used to show the color as the background color of the body element. ' , 
        img: require("../assets/img/colorGenerator.png"),
        git: true,
        gitLink: "https://github.com/P1wP/COLOR_GENERATOR",
        live: true,
        liveLink: "http://www.noob-at-work.com/fun/Hexcolor/index.html",
        html: true,
        js: true,
        react: false,
        sass: false,
        css: false,
        grunt: false,
        py: false,
        boot: false
    },
    {id: 8, 
        title: 'Practice with JavaScript',
        discription: 'Used JavaScript to fetch an API and populate a website with data. Give the page some time to load. It is...ehmm, Slow.' , 
        img: require("../assets/img/card_game.png"),
        git: true,
        gitLink: "https://github.com/P1wP/JavaScript_1",
        live: true,
        liveLink: "http://www.noob-at-work.com/noroff/js_1/ca/index.html",
        html: false,
        js: false,
        react: true,
        sass: true,
        css: false,
        grunt: false,
        py: false,
        boot: true
    },
    {id: 9, 
        title: 'React.js introduction',
        discription: 'This was part of my js frameworks course. I had to make a reactApp that lets u serach for, view details of a game.' , 
        img: require("../assets/img/react_game.png"),
        git: true,
        gitLink: "https://github.com/P1wP/Joachim-Satre-js-frameworks-ca",
        live: true,
        liveLink: "https://elated-bohr-b11ac9.netlify.app/",
        html: false,
        js: false,
        react: true,
        sass: true,
        css: false,
        grunt: false,
        py: false,
        boot: true
    },
    
    

]